# Generated by Django 3.2.4 on 2021-06-06 08:06

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.IntegerField(default=backend.models.generate_mrn, verbose_name='MRN')),
                ('national_id', models.CharField(max_length=50, unique=True, verbose_name='National id')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationality')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Unknown', 'Unknown')], max_length=50, verbose_name='Gender')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('first_name', models.CharField(max_length=50, verbose_name='Firtst Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('onset_date', models.DateField(auto_now=True, verbose_name='Onset Date')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Phone')),
                ('disease', models.CharField(max_length=50, verbose_name='Disease')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='adding_date',
            field=models.DateField(auto_now=True, verbose_name='Adding date'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='adding_date',
            field=models.DateField(auto_now=True, verbose_name='Adding date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='National ID'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('note', models.TextField(verbose_name='Additional informations')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='Submission date')),
                ('direction', models.CharField(choices=[('Forward', 'Forward'), ('Reverse', 'Reverse'), ('Single', 'Single')], max_length=50, verbose_name='Direction')),
                ('sequnce', models.FileField(blank=True, upload_to=backend.models.upload_to, verbose_name='Sequence')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient', verbose_name='Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.doctor', verbose_name='Doctor'),
        ),
        migrations.CreateModel(
            name='GeneExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=50, verbose_name='Gene')),
                ('expression', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Expression level')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sequence', verbose_name='Sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
