# Generated by Django 3.2.4 on 2021-06-06 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210606_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneexpression',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Adding date'),
            preserve_default=False,
        ),
    ]
