# Generated by Django 3.2.4 on 2021-06-05 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='adding_date',
            field=models.DateField(auto_now=True, verbose_name='Adding date'),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.CharField(default='', max_length=50, verbose_name='Disease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcher',
            name='adding_date',
            field=models.DateField(auto_now=True, verbose_name='Adding date'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('note', models.TextField(verbose_name='Additional informations')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
