# Generated by Django 3.2.4 on 2021-06-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='direction',
        ),
    ]
