# Generated by Django 3.2.4 on 2021-06-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_sequence_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='direction',
            field=models.CharField(choices=[('Forward', 'Forward'), ('Reverse', 'Reverse'), ('Single', 'Single')], default='Single', max_length=50, verbose_name='Direction'),
            preserve_default=False,
        ),
    ]
